# test_pdf.py
import sys
import os

# Asegurarse de que puede importar desde services
sys.path.insert(0, os.path.dirname(__file__))

from services.pdf_generator_reportlab import generar_pdf_con_datos

# Datos de prueba
datos_prueba = {
    "numero": "EST-1125-0001-ULTRA-EXTREMO-TEST-LARGO-DEMO-VERSION-999999",
    "fecha_emision": "23/11/2025",
    "fecha_vencimiento": "23/12/2025",
    "vigencia_dias": 30,
    "cliente": {
        "nombre": "Corporación Internacional de Suministros y Servicios Técnicos Avanzados para la Industria Automotriz, Energética y de Construcción",
        "rnc": "1-01-12345-6-EXTREMO-999999999",
        "correo": "contacto.extremo@megacorporacionglobal.com",
        "telefono": "(809) 555-1234 EXT-999999",
        "direccion": "Av. Principal #123, Torre Empresarial Global, Piso 45, Suite 4501, Santo Domingo, República Dominicana, Código Postal 10101"
    },
    "descripcion": (
        "Cotización extremadamente detallada para la instalación, modernización y optimización de sistemas eléctricos, "
        "de telecomunicaciones y respaldo energético en un complejo corporativo multinacional de 20 pisos. "
        "Incluye diseño de paneles eléctricos inteligentes, cableado estructurado de última generación, "
        "implementación de sistemas redundantes de energía con UPS y generadores, integración de domótica avanzada, "
        "sensores IoT para monitoreo en tiempo real, y protocolos de seguridad digital y física para garantizar "
        "la continuidad operativa en condiciones críticas."
    ),
    "items": [
        {
            "alcance": (
                "Instalación de panel eléctrico principal de 400A con breakers inteligentes jvhjvjhvjhvjhvjh vuygvujyhvjhvjhv yvyhguyvikgvkugbikugbi ihuhkuiubgikugbikgbi iugigbikbgugbiugiug iugiugiuggiugiugiug iugygiuiugiugiugiug iguigiugoiug, "
                "monitoreo remoto vía aplicación móvil, redundancia en cada piso, "
               
            ),
            "monto": 175000.00
        },
        {
            "alcance": (
                "Cableado estructurado completo para 250 puntos de red, 150 puntos eléctricos, "
                "fibra óptica de alta velocidad, certificación internacional de calidad, "
                "y pruebas de rendimiento con simulaciones de carga máxima."
            ),
            "monto": 325000.00
        },
        {
            "alcance": (
                "Sistema de respaldo UPS modular de 50KVA con banco de baterías de litio de alta densidad, "
                "capacidad de autonomía de 12 horas, integración con generador diésel de 200KVA, "
                "y monitoreo inteligente con alertas en tiempo real."
            ),
            "monto": 280000000000.00
        },
        {
            "alcance": (
                "Implementación de domótica avanzada para control de iluminación, climatización, "
                "acceso biométrico, cámaras de seguridad con inteligencia artificial, "
                "y panel de control centralizado con interfaz gráfica intuitiva."
            ),
            "monto": 450000.00
        },
        {
            "alcance": (
                "Instalación de sensores IoT para monitoreo de consumo energético, "
                "detección de fallos, análisis predictivo de mantenimiento, "
                "y generación automática de reportes para la gerencia."
            ),
            "monto": 210000.00
        },
        {
            "alcance": (
                "Capacitación avanzada al personal técnico y administrativo en el uso de los sistemas instalados, "
                "incluyendo manuales digitales interactivos, simulaciones de emergencia, "
                "y soporte remoto durante los primeros 12 meses."
            ),
            "monto": 95000.00
        }
    ],
    "terminos": [
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",

        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        
        "La presente cotización tiene una vigencia estricta de 30 días a partir de su emisión, sin excepciones.",
        "Los precios incluyen ITBIS (18%) y cualquier otro impuesto aplicable según la legislación vigente.",
        "Forma de pago: 50% anticipo, 30% durante la ejecución del proyecto, 20% contra entrega final con certificación de calidad.",
        "Tiempo de entrega: 45 días hábiles después de confirmado el pedido, sujeto a disponibilidad de equipos importados.",
        "Garantía: 24 meses en equipos, 12 meses en mano de obra, con soporte técnico remoto y presencial.",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Confidencialidad: toda la información técnica y comercial contenida en esta propuesta es estrictamente confidencial.",
        "Confidencialidad: toda la información técnica y comercial contenida en esta propuesta es estrictamente confidencial.", 
        "Confidencialidad: toda la información técnica y comercial contenida en esta propuesta es estrictamente confidencial.",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente. ",
        "Confidencialidad: toda la información técnica y comercial contenida en esta propuesta es estrictamente confidencial.",
        "Confidencialidad: toda la información técnica y comercial contenida en esta propuesta es estrictamente confidencial.",
        "La presente cotización tiene una vigencia estricta de 30 días a partir de su emisión, sin excepciones.",
        "Los precios incluyen ITBIS (18%) y cualquier otro impuesto aplicable según la legislación vigente.",
        "Forma de pago: 50% anticipo, 30% durante la ejecución del proyecto, 20% contra entrega final con certificación de calidad.",
        "Tiempo de entrega: 45 días hábiles después de confirmado el pedido, sujeto a disponibilidad de equipos importados.",
        "Garantía: 24 meses en equipos, 12 meses en mano de obra, con soporte técnico remoto y presencial.",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente.",
        "Confidencialidad: toda la información técnica y comercial contenida en esta propuesta es estrictamente confidencial.",
        "Confidencialidad: toda la información técnica y comercial contenida en esta propuesta es estrictamente confidencial.", 
        "Confidencialidad: toda la información técnica y comercial contenida en esta propuesta es estrictamente confidencial.",
        "Confidencialidad: toda la información técnica y comercial contenida en esta propuesta es estrictamente confidencial.",
        "Confidencialidad: toda la información técnica y comercial contenida en esta propuesta es estrictamente confidencial.",
        "La presente cotización tiene una vigencia estricta de 30 días a partir de su emisión, sin excepciones.",
        "Los precios incluyen ITBIS (18%) y cualquier otro impuesto aplicable según la legislación vigente.",
        "Forma de pago: 50% anticipo, 30% durante la ejecución del proyecto, 20% contra entrega final con certificación de calidad.",
        "Tiempo de entrega: 45 días hábiles después de confirmado el pedido, sujeto a disponibilidad de equipos importados.",
        "Garantía: 24 meses en equipos, 12 meses en mano de obra, con soporte técnico remoto y presencial.",
        "Condiciones especiales: cualquier modificación solicitada por el cliente fuera del alcance inicial será cotizada adicionalmente.",
        "Confidencialidad: toda la información técnica y comercial contenida en esta propuesta es estrictamente confidencial.",
        "Confidencialidad: toda la información técnica y comercial contenida en esta propuesta es estrictamente confidencial.", 
        "Confidencialidad: toda la información técnica y comercial contenida en esta propuesta es estrictamente confidencial.",
        "Confidencialidad: toda la información técnica y comercial contenida en esta propuesta es estrictamente confidencial.",
        "Confidencialidad: toda la información técnica y comercial contenida en esta propuesta es estrictamente confidencial.",
        
    ],
    "subtotal": 153500000000.00,
    "itbis": 276300000000.00,
    "total": 181130000000000.00
}

if __name__ == "__main__":
    print("🔧 Generando PDF de prueba...")
    try:
        output_dir = "pdf_generados"
        os.makedirs(output_dir, exist_ok=True)
        ruta_salida = os.path.join(output_dir, "TEST_cotizacion.pdf")

        ruta = generar_pdf_con_datos(datos_prueba, ruta_salida)
        print(f"✅ PDF generado exitosamente: {ruta}")
        print("📄 Abre la carpeta pdf_generados/ para verlo")
    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()